### ISSUE TITLE
Rename it?

### ISSUE THREAD

**Issue by autarch** [maxmind/App-GHPT#1]
I think "SubmitWork" is a bit too generic for something that will go on CPAN. I was thinking of something like "Pivothub" or "Githubotal" or something that combines the two names like that.

**Comment by oschwald** [comment]
:+1: I think we should also create a team or something for outside collaborators.

**Comment by 2shortplanks** [comment]
I couldn't decide on a good name, so I called it whatever first came to
mind because I *knew* whatever I picked someone would come up with a better
one.  Rename away!

On Mon, Apr 17, 2017 at 10:52 PM, Gregory Oschwald <notifications@github.com

**Comment by oschwald** [comment]
I think I might take back my team comment. AFAICT, GitHub doesn't have a very good way to create a "team" of outside collaborators without restricting the permissions of other  people in the organization to create repos, etc.

**Comment by autarch** [comment]
I think the only way to make a separate team is to make a separate organization and transfer the repo to it, which we could do easily enough.

**Comment by autarch** [comment]
Also, can I get admin access to this and the other repo?

**Comment by jasonketola** [comment]
Will you need admin access indefinitely? Or can we provide it for, say, two weeks?

**Comment by autarch** [comment]
Ideally indefinitely. That way I'm able to do things like manage integrations with Travis, etc. There's not really any risk here. All I need is admin for a couple repos, not to the whole org, which is an entirely separate permission.

**Comment by autarch** [comment]
There are already two projects named "Pivothub". The name "Githubotal" might work, or we could do "App::GHPT" with "gh-pt" (or pt-gh) as the CLI command. If no one cares I'll just pick one by tomorrow.

**Comment by jasonketola** [comment]
Admin access provided.

**Comment by autarch** [comment]
Done.
