### ISSUE TITLE
Handling of character encoding when displaying data from PT in the terminal should be fixed

### ISSUE THREAD

**Issue by oschwald** [maxmind/App-GHPT#16]
For example:

```
Note: 1 chore is not shown here (chores by definition do not require review).
Country name of Reunion and R�union are cleaned to "RE"

https://www.pivotaltracker.com/story/show/149683231

A/C:
* Country name of Reunion and R�union are cleaned to "RE"
```
The correct characters _do_ show up in the GitHub PR. My `$LANG` is `en_US.UTF-8`.

**Comment by autarch** [comment]
I think this might be as simple as doing `binmode ':encoding(UTF-8)', STDOUT` at the start the `App::GHPT::WorkSubmitter->run` method.

**Comment by oschwald** [comment]
Isn't that already done by [Ourperl](https://github.com/maxmind/App-GHPT/blob/master/lib/App/GHPT/Wrapper/Ourperl.pm#L23)?

**Comment by autarch** [comment]
Ah, good point. I think the problem may actually be in `WebService::PivotalTracker` then. Maybe it needs to decode the data returned by the PT API.

**Comment by horgh** [comment]
I assume this is the same bug, but I see something slightly different today:

When I have a story with a name like "test story  → g" I see this when showing the list of stories:

```
Wide character in print at /opt/perl5.26.3/lib/site_perl/5.26.3/Term/Choose.pm line 1085.
```

I see it again if I select a story with the character in the description, although a different line:

```
Wide character in print at /opt/perl5.26.3/lib/site_perl/5.26.3/Term/Choose.pm line 774.
```

**Comment by oschwald** [comment]
I think this is caused by [this 11-year-old `IPC::Run3` issue](https://rt.cpan.org/Ticket/Display.html?id=69011).

**Comment by oschwald** [comment]
We are archiving this repo and closing all issues as part of that. If you are interested in maintaining this distribution, please contact support@maxmind.com.
