### ISSUE TITLE
Can't locate App/GHPT/Wrapper/Ourperl.pm

### ISSUE THREAD

**Issue by damianesteban** [maxmind/App-GHPT#19]
This looks like a fantastic tool but I'm having some trouble getting started. When I try to run `gh-pt.pl` I receive the following error:

```
Can't locate App/GHPT/Wrapper/Ourperl.pm in @INC (you may need to install the App::GHPT::Wrapper::Ourperl module)
```

And after some path info it ends with the following:

```
BEGIN failed--compilation aborted at ./gh-pt.pl line 3.
```

My knowledge of perl is limited so I'm not sure if I am installing the libraries correctly.

**Comment by autarch** [comment]
Did you install this using the a Perl module installation tool? I'm guessing you didn't.

Try installing cpanm:

```
$>  curl -L https://cpanmin.us | perl - App::cpanminus
```

Then run `cpanm -n --sudo App::GHPT`. That should get it installed against your system Perl (assuming you're on a Unix or macOS system).
