### ISSUE TITLE
Missing dep on LWP::Protocol::https

### ISSUE THREAD

**Issue by autarch** [maxmind/App-GHPT#20]

**Comment by autarch** [comment]
I was helping a co-worker install this. The install went fine, but then when running it blew up because this module was missing.

**Comment by oschwald** [comment]
Thanks for the report! A PR would be great. :slightly_smiling_face:

**Comment by autarch** [comment]
Heh, I mostly filed this to remind myself to work on it when I have a chance.

**Comment by autarch** [comment]
Actually, I realized this must be an issue with WebService::PivotalTracker, not this distro.
