### ISSUE TITLE
Munging the project name seems incorrect

### ISSUE THREAD

**Issue by horgh** [maxmind/App-GHPT#21]
[Here](https://github.com/maxmind/App-GHPT/blob/master/lib/App/GHPT/WorkSubmitter.pm#L111) we replace spaces with dashes in the project name provided before comparing it with what we received from PT.

Is that necessary? It seems to not find the project when I do that. e.g.,:

```
$ submit-work.pl --project 'My Sample Project'                          
Could not find a project id for project named My Sample Project at [snip]WorkSubmitter.pm line 114.
```

If I remove that logic, it does find the project. I'm not sure if there's a need for this I'm missing though.

(Also, we should probably escape metacharacters in the regex there)

**Comment by klp2** [comment]
In the past, there was a default project, and if you were submitting for any other project you had to include the name. I suspect it was deemed easier to write `--project my-cool-project` than `--project 'My Cool Project'`. I still would prefer the former if I had to type it out frequently, but now that we look at all projects by default maybe it doesn't matter as much.
