### ISSUE TITLE
Make requests to PT in parallel

### ISSUE THREAD

**Issue by 2shortplanks** [maxmind/App-GHPT#9]
In order to speed things up, when possible requests to PT for info on projects should be made in parallel.

This can be done with `Parallel::ForkManager` or by altering the modules / code we use to make web requests to PT so that it uses a non-blocking / parallel type user agent and/or event loop.

**Comment by oschwald** [comment]
Although I am not sure we will ever get around to this, Pivotal Tracker does have an [aggregator API](https://www.pivotaltracker.com/help/api/#top:~:text=Using%20the%20GET%2DRequest%20Aggregator).

**Comment by oschwald** [comment]
We are archiving this repo and closing all issues as part of that. If you are interested in maintaining this distribution, please contact support@maxmind.com.
